### PR TITLE
recoiled back to chapter 5 for table layout practice 

### PR DESCRIPTION
**Pull request by elroykanye**

### CODE REVIEW

**Comment by elroykanye** [comment]
Waiting for merge hombre.
Your own exercises are not in your named folder too.

**Comment by Jardon237** [comment]
Hahaha getout. It's ma repo. I have the say on directory name. If like
don't contribute. 🤣🤣

Sorry na joke🙏

**Comment by elroykanye** [comment]
Okay. Please merge it then.

**Comment by elroykanye** [comment]
Yo please I'm waiting for you to merge pr

**Pull request merged**
